spring.application.name=gamelist-api

# Puerto para Cloud Run
server.port=${PORT:8080}

# 🔥 CONEXION CORRECTA PARA CLOUD RUN
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# 🔧 Pool pequeño (recomendado en Cloud Run)
spring.datasource.hikari.maximum-pool-size=2

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true