spring.application.name=gamelist-api

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/gamelist
spring.datasource.username=postgres
spring.datasource.password=123456789

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true